default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ats_development

test:
  <<: *default
  database: ats_test

production:
  <<: *default
  database: ats_production
  username: ats
  password: <%= ENV["ATS_DATABASE_PASSWORD"] %>
